# Définit la version minimale de la plateforme iOS
platform :ios, '13.0'

target 'Runner' do
  # Utiliser des frameworks dynamiques (requis pour de nombreux plugins)
  use_frameworks!
  use_modular_headers!

  # Ajoute tous les Pods nécessaires pour les plugins Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Configuration pour les tests
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods pour les tests (ajoutez ici si nécessaire)
  end
end
