// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxZ2gnDY1QFxvo-oBT5zvY4f_tgjX--M',
    appId: '1:996086520169:web:64880f25d905fcb44b85f8',
    messagingSenderId: '996086520169',
    projectId: 'finesse-772de',
    authDomain: 'finesse-772de.firebaseapp.com',
    storageBucket: 'finesse-772de.firebasestorage.app',
    measurementId: 'G-85BC7ZQBE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1_0G8VkEjbG_78jUwl8fyavzPk8sIpY',
    appId: '1:996086520169:android:8cf54066a6f01dd44b85f8',
    messagingSenderId: '996086520169',
    projectId: 'finesse-772de',
    storageBucket: 'finesse-772de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCReATnUCzUbqYbsV5omPNuwJf9yAA79k',
    appId: '1:996086520169:ios:e59f4cf9826dc80b4b85f8',
    messagingSenderId: '996086520169',
    projectId: 'finesse-772de',
    storageBucket: 'finesse-772de.firebasestorage.app',
    iosBundleId: 'com.example.finesseFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCReATnUCzUbqYbsV5omPNuwJf9yAA79k',
    appId: '1:996086520169:ios:e59f4cf9826dc80b4b85f8',
    messagingSenderId: '996086520169',
    projectId: 'finesse-772de',
    storageBucket: 'finesse-772de.firebasestorage.app',
    iosBundleId: 'com.example.finesseFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUxZ2gnDY1QFxvo-oBT5zvY4f_tgjX--M',
    appId: '1:996086520169:web:09de568d47f7d9ea4b85f8',
    messagingSenderId: '996086520169',
    projectId: 'finesse-772de',
    authDomain: 'finesse-772de.firebaseapp.com',
    storageBucket: 'finesse-772de.firebasestorage.app',
    measurementId: 'G-5GMTKGK3D2',
  );
}
